root = "."
tmp_dir = "tmp"

[build]
bin = "tmp/server"
cmd = "go build -o ./tmp/server ./server"
include_ext = ["go", "html", "tmpl", "tpl", "toml", "json"]
include_dir = ["server"]
exclude_dir = ["tmp", "vendor", "node_modules", "dist", ".git"]
delay = 200

[log]
time = true

[color]
main = "yellow"
watcher = "cyan"
build = "green"
app = "magenta"

[misc]
clean_on_exit = true
poll = true
